syntax = "proto3";
package kratos.api;

option go_package = "go-ai-agent/app/rag-api/internal/conf;conf";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
  Data data = 2;
}

message Server {
  message HTTP {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  HTTP http = 1;
  GRPC grpc = 2;
}

message Data {
  message Model {
    string provider = 1;
    string api_key = 2;
    string base_url = 3;
    string model_name = 4;
  }
  message Milvus {
    string addr = 1;
    string collection = 2;
    string username = 3;
    string password = 4;
  }
  message Embedder {
    string base_url = 1;
    string model = 2;
    int32 dim = 3;
  }
  Model model = 1;
  Milvus milvus = 2;
  Embedder embedder = 3;
}
