services:
  ollama:
    image: ollama/ollama:0.32.10
    container_name: ollama

    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      # 持久化 Ollama 下载的模型
      - ../../tmp/ollama-data:/root/.ollama

    # 将 NVIDIA GPU 提供给 Ollama
    # 需要 Docker Compose 2.30.0+
    # gpus: all

volumes:
  ollama-data: