// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"go-ai-agent/app/rag-api/internal/biz"
	"go-ai-agent/app/rag-api/internal/conf"
	"go-ai-agent/app/rag-api/internal/data"
	"go-ai-agent/app/rag-api/internal/server"
	"go-ai-agent/app/rag-api/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	documentLoader := data.NewDocumentLoader(confData)
	db := data.NewMySQL(confData)
	client, err := data.NewMilvusClient(confData)
	if err != nil {
		return nil, nil, err
	}
	embedderClient := data.NewEmbeddingClient(confData)
	dataData, cleanup, err := data.NewData(db, client, embedderClient)
	if err != nil {
		return nil, nil, err
	}
	embedder := data.NewEmbedderRepo(dataData, logger)
	vectorStore, err := data.NewVectorStore(dataData, confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	llm := data.NewLLMRepo(confData)
	documentMetadataRepo := data.NewDocumentMetadataRepo(dataData)
	documentLockRepo := data.NewDocumentLockRepo()
	ragConfig := data.NewRAGConfig(confData)
	ragUsecase := biz.NewRAGUsecase(documentLoader, embedder, vectorStore, llm, documentMetadataRepo, documentLockRepo, ragConfig, logger)
	ragService := service.NewRagService(ragUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, ragService)
	httpServer := server.NewHTTPServer(confServer, ragService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
