// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ai-agent/app/rag-api/internal/data/dal/model"
)

func newRagDocumentMetadatum(db *gorm.DB, opts ...gen.DOOption) ragDocumentMetadatum {
	_ragDocumentMetadatum := ragDocumentMetadatum{}

	_ragDocumentMetadatum.ragDocumentMetadatumDo.UseDB(db, opts...)
	_ragDocumentMetadatum.ragDocumentMetadatumDo.UseModel(&model.RagDocumentMetadatum{})

	tableName := _ragDocumentMetadatum.ragDocumentMetadatumDo.TableName()
	_ragDocumentMetadatum.ALL = field.NewAsterisk(tableName)
	_ragDocumentMetadatum.DocumentID = field.NewString(tableName, "document_id")
	_ragDocumentMetadatum.SourcePath = field.NewString(tableName, "source_path")
	_ragDocumentMetadatum.Title = field.NewString(tableName, "title")
	_ragDocumentMetadatum.CollectionName = field.NewString(tableName, "collection_name")
	_ragDocumentMetadatum.EmbeddingModel = field.NewString(tableName, "embedding_model")
	_ragDocumentMetadatum.EmbeddingDim = field.NewInt64(tableName, "embedding_dim")
	_ragDocumentMetadatum.ChunkSize = field.NewInt64(tableName, "chunk_size")
	_ragDocumentMetadatum.ChunkOverlap = field.NewInt64(tableName, "chunk_overlap")
	_ragDocumentMetadatum.LastIndexedAt = field.NewTime(tableName, "last_indexed_at")

	_ragDocumentMetadatum.fillFieldMap()

	return _ragDocumentMetadatum
}

// ragDocumentMetadatum rag document 元数据
type ragDocumentMetadatum struct {
	ragDocumentMetadatumDo

	ALL            field.Asterisk
	DocumentID     field.String
	SourcePath     field.String // document 路径
	Title          field.String // document 标题
	CollectionName field.String // milvus collection 名称
	EmbeddingModel field.String // 对 chunk 进行 embed 的模型名称
	EmbeddingDim   field.Int64  // embed 切分出的向量维度
	ChunkSize      field.Int64  // chunk 大小,  即一个 chunk 的长度
	ChunkOverlap   field.Int64  // 一个 chunk 包含前一个 chunk 的多少个字符
	LastIndexedAt  field.Time   // 上次为该 document chunk 进行向量化的时间

	fieldMap map[string]field.Expr
}

func (r ragDocumentMetadatum) Table(newTableName string) *ragDocumentMetadatum {
	r.ragDocumentMetadatumDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ragDocumentMetadatum) As(alias string) *ragDocumentMetadatum {
	r.ragDocumentMetadatumDo.DO = *(r.ragDocumentMetadatumDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ragDocumentMetadatum) updateTableName(table string) *ragDocumentMetadatum {
	r.ALL = field.NewAsterisk(table)
	r.DocumentID = field.NewString(table, "document_id")
	r.SourcePath = field.NewString(table, "source_path")
	r.Title = field.NewString(table, "title")
	r.CollectionName = field.NewString(table, "collection_name")
	r.EmbeddingModel = field.NewString(table, "embedding_model")
	r.EmbeddingDim = field.NewInt64(table, "embedding_dim")
	r.ChunkSize = field.NewInt64(table, "chunk_size")
	r.ChunkOverlap = field.NewInt64(table, "chunk_overlap")
	r.LastIndexedAt = field.NewTime(table, "last_indexed_at")

	r.fillFieldMap()

	return r
}

func (r *ragDocumentMetadatum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ragDocumentMetadatum) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["document_id"] = r.DocumentID
	r.fieldMap["source_path"] = r.SourcePath
	r.fieldMap["title"] = r.Title
	r.fieldMap["collection_name"] = r.CollectionName
	r.fieldMap["embedding_model"] = r.EmbeddingModel
	r.fieldMap["embedding_dim"] = r.EmbeddingDim
	r.fieldMap["chunk_size"] = r.ChunkSize
	r.fieldMap["chunk_overlap"] = r.ChunkOverlap
	r.fieldMap["last_indexed_at"] = r.LastIndexedAt
}

func (r ragDocumentMetadatum) clone(db *gorm.DB) ragDocumentMetadatum {
	r.ragDocumentMetadatumDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r ragDocumentMetadatum) replaceDB(db *gorm.DB) ragDocumentMetadatum {
	r.ragDocumentMetadatumDo.ReplaceDB(db)
	return r
}

type ragDocumentMetadatumDo struct{ gen.DO }

type IRagDocumentMetadatumDo interface {
	gen.SubQuery
	Debug() IRagDocumentMetadatumDo
	WithContext(ctx context.Context) IRagDocumentMetadatumDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRagDocumentMetadatumDo
	WriteDB() IRagDocumentMetadatumDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRagDocumentMetadatumDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRagDocumentMetadatumDo
	Not(conds ...gen.Condition) IRagDocumentMetadatumDo
	Or(conds ...gen.Condition) IRagDocumentMetadatumDo
	Select(conds ...field.Expr) IRagDocumentMetadatumDo
	Where(conds ...gen.Condition) IRagDocumentMetadatumDo
	Order(conds ...field.Expr) IRagDocumentMetadatumDo
	Distinct(cols ...field.Expr) IRagDocumentMetadatumDo
	Omit(cols ...field.Expr) IRagDocumentMetadatumDo
	Join(table schema.Tabler, on ...field.Expr) IRagDocumentMetadatumDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRagDocumentMetadatumDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRagDocumentMetadatumDo
	Group(cols ...field.Expr) IRagDocumentMetadatumDo
	Having(conds ...gen.Condition) IRagDocumentMetadatumDo
	Limit(limit int) IRagDocumentMetadatumDo
	Offset(offset int) IRagDocumentMetadatumDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRagDocumentMetadatumDo
	Unscoped() IRagDocumentMetadatumDo
	Create(values ...*model.RagDocumentMetadatum) error
	CreateInBatches(values []*model.RagDocumentMetadatum, batchSize int) error
	Save(values ...*model.RagDocumentMetadatum) error
	First() (*model.RagDocumentMetadatum, error)
	Take() (*model.RagDocumentMetadatum, error)
	Last() (*model.RagDocumentMetadatum, error)
	Find() ([]*model.RagDocumentMetadatum, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RagDocumentMetadatum, err error)
	FindInBatches(result *[]*model.RagDocumentMetadatum, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RagDocumentMetadatum) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRagDocumentMetadatumDo
	Assign(attrs ...field.AssignExpr) IRagDocumentMetadatumDo
	Joins(fields ...field.RelationField) IRagDocumentMetadatumDo
	Preload(fields ...field.RelationField) IRagDocumentMetadatumDo
	FirstOrInit() (*model.RagDocumentMetadatum, error)
	FirstOrCreate() (*model.RagDocumentMetadatum, error)
	FindByPage(offset int, limit int) (result []*model.RagDocumentMetadatum, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRagDocumentMetadatumDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ragDocumentMetadatumDo) Debug() IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Debug())
}

func (r ragDocumentMetadatumDo) WithContext(ctx context.Context) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ragDocumentMetadatumDo) ReadDB() IRagDocumentMetadatumDo {
	return r.Clauses(dbresolver.Read)
}

func (r ragDocumentMetadatumDo) WriteDB() IRagDocumentMetadatumDo {
	return r.Clauses(dbresolver.Write)
}

func (r ragDocumentMetadatumDo) Session(config *gorm.Session) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Session(config))
}

func (r ragDocumentMetadatumDo) Clauses(conds ...clause.Expression) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ragDocumentMetadatumDo) Returning(value interface{}, columns ...string) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ragDocumentMetadatumDo) Not(conds ...gen.Condition) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ragDocumentMetadatumDo) Or(conds ...gen.Condition) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ragDocumentMetadatumDo) Select(conds ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ragDocumentMetadatumDo) Where(conds ...gen.Condition) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ragDocumentMetadatumDo) Order(conds ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ragDocumentMetadatumDo) Distinct(cols ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ragDocumentMetadatumDo) Omit(cols ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ragDocumentMetadatumDo) Join(table schema.Tabler, on ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ragDocumentMetadatumDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ragDocumentMetadatumDo) RightJoin(table schema.Tabler, on ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ragDocumentMetadatumDo) Group(cols ...field.Expr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ragDocumentMetadatumDo) Having(conds ...gen.Condition) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ragDocumentMetadatumDo) Limit(limit int) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ragDocumentMetadatumDo) Offset(offset int) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ragDocumentMetadatumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ragDocumentMetadatumDo) Unscoped() IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ragDocumentMetadatumDo) Create(values ...*model.RagDocumentMetadatum) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ragDocumentMetadatumDo) CreateInBatches(values []*model.RagDocumentMetadatum, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ragDocumentMetadatumDo) Save(values ...*model.RagDocumentMetadatum) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ragDocumentMetadatumDo) First() (*model.RagDocumentMetadatum, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RagDocumentMetadatum), nil
	}
}

func (r ragDocumentMetadatumDo) Take() (*model.RagDocumentMetadatum, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RagDocumentMetadatum), nil
	}
}

func (r ragDocumentMetadatumDo) Last() (*model.RagDocumentMetadatum, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RagDocumentMetadatum), nil
	}
}

func (r ragDocumentMetadatumDo) Find() ([]*model.RagDocumentMetadatum, error) {
	result, err := r.DO.Find()
	return result.([]*model.RagDocumentMetadatum), err
}

func (r ragDocumentMetadatumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RagDocumentMetadatum, err error) {
	buf := make([]*model.RagDocumentMetadatum, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ragDocumentMetadatumDo) FindInBatches(result *[]*model.RagDocumentMetadatum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ragDocumentMetadatumDo) Attrs(attrs ...field.AssignExpr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ragDocumentMetadatumDo) Assign(attrs ...field.AssignExpr) IRagDocumentMetadatumDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ragDocumentMetadatumDo) Joins(fields ...field.RelationField) IRagDocumentMetadatumDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ragDocumentMetadatumDo) Preload(fields ...field.RelationField) IRagDocumentMetadatumDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ragDocumentMetadatumDo) FirstOrInit() (*model.RagDocumentMetadatum, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RagDocumentMetadatum), nil
	}
}

func (r ragDocumentMetadatumDo) FirstOrCreate() (*model.RagDocumentMetadatum, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RagDocumentMetadatum), nil
	}
}

func (r ragDocumentMetadatumDo) FindByPage(offset int, limit int) (result []*model.RagDocumentMetadatum, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ragDocumentMetadatumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ragDocumentMetadatumDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ragDocumentMetadatumDo) Delete(models ...*model.RagDocumentMetadatum) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ragDocumentMetadatumDo) withDO(do gen.Dao) *ragDocumentMetadatumDo {
	r.DO = *do.(*gen.DO)
	return r
}
