// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rag/v1/rag.proto

package ragv1

import (
	v1 "go-ai-agent/app/rag-api/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonResp    *v1.CommonResp         `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetCommonResp() *v1.CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type ImportDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDocumentRequest) Reset() {
	*x = ImportDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDocumentRequest) ProtoMessage() {}

func (x *ImportDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDocumentRequest.ProtoReflect.Descriptor instead.
func (*ImportDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *ImportDocumentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ImportDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonResp    *v1.CommonResp         `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDocumentResponse) Reset() {
	*x = ImportDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDocumentResponse) ProtoMessage() {}

func (x *ImportDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDocumentResponse.ProtoReflect.Descriptor instead.
func (*ImportDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *ImportDocumentResponse) GetCommonResp() *v1.CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonResp    *v1.CommonResp         `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Citations     []*Citation            `protobuf:"bytes,3,rep,name=citations,proto3" json:"citations,omitempty"`
	SearchResults []*SearchResult        `protobuf:"bytes,4,rep,name=search_results,json=searchResults,proto3" json:"search_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *AskResponse) GetCommonResp() *v1.CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskResponse) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *AskResponse) GetSearchResults() []*SearchResult {
	if x != nil {
		return x.SearchResults
	}
	return nil
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceFile    string                 `protobuf:"bytes,1,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *Citation) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *Citation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Citation) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceFile    string                 `protobuf:"bytes,1,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x16common/v1/common.proto\"\x0f\n" +
	"\rHealthRequest\"H\n" +
	"\x0eHealthResponse\x126\n" +
	"\vcommon_resp\x18\x01 \x01(\v2\x15.common.v1.CommonRespR\n" +
	"commonResp\"0\n" +
	"\x15ImportDocumentRequest\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tB\x03\xe0A\x02R\x04path\"P\n" +
	"\x16ImportDocumentResponse\x126\n" +
	"\vcommon_resp\x18\x01 \x01(\v2\x15.common.v1.CommonRespR\n" +
	"commonResp\"G\n" +
	"\n" +
	"AskRequest\x12\x1f\n" +
	"\bquestion\x18\x01 \x01(\tB\x03\xe0A\x02R\bquestion\x12\x18\n" +
	"\x05top_k\x18\x02 \x01(\x05B\x03\xe0A\x02R\x04topK\"\xca\x01\n" +
	"\vAskResponse\x126\n" +
	"\vcommon_resp\x18\x01 \x01(\v2\x15.common.v1.CommonRespR\n" +
	"commonResp\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12.\n" +
	"\tcitations\x18\x03 \x03(\v2\x10.rag.v1.CitationR\tcitations\x12;\n" +
	"\x0esearch_results\x18\x04 \x03(\v2\x14.rag.v1.SearchResultR\rsearchResults\"b\n" +
	"\bCitation\x12\x1f\n" +
	"\vsource_file\x18\x01 \x01(\tR\n" +
	"sourceFile\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x03R\n" +
	"chunkIndex\"\x96\x01\n" +
	"\fSearchResult\x12\x1f\n" +
	"\vsource_file\x18\x01 \x01(\tR\n" +
	"sourceFile\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x03R\n" +
	"chunkIndex\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent2\x9b\x02\n" +
	"\n" +
	"RagService\x12O\n" +
	"\x06Health\x12\x15.rag.v1.HealthRequest\x1a\x16.rag.v1.HealthResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/health\x12t\n" +
	"\x0eImportDocument\x12\x1d.rag.v1.ImportDocumentRequest\x1a\x1e.rag.v1.ImportDocumentResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/documents/import\x12F\n" +
	"\x03Ask\x12\x12.rag.v1.AskRequest\x1a\x13.rag.v1.AskResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/askB*Z(go-ai-agent/app/rag-api/api/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rag_v1_rag_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: rag.v1.HealthRequest
	(*HealthResponse)(nil),         // 1: rag.v1.HealthResponse
	(*ImportDocumentRequest)(nil),  // 2: rag.v1.ImportDocumentRequest
	(*ImportDocumentResponse)(nil), // 3: rag.v1.ImportDocumentResponse
	(*AskRequest)(nil),             // 4: rag.v1.AskRequest
	(*AskResponse)(nil),            // 5: rag.v1.AskResponse
	(*Citation)(nil),               // 6: rag.v1.Citation
	(*SearchResult)(nil),           // 7: rag.v1.SearchResult
	(*v1.CommonResp)(nil),          // 8: common.v1.CommonResp
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	8, // 0: rag.v1.HealthResponse.common_resp:type_name -> common.v1.CommonResp
	8, // 1: rag.v1.ImportDocumentResponse.common_resp:type_name -> common.v1.CommonResp
	8, // 2: rag.v1.AskResponse.common_resp:type_name -> common.v1.CommonResp
	6, // 3: rag.v1.AskResponse.citations:type_name -> rag.v1.Citation
	7, // 4: rag.v1.AskResponse.search_results:type_name -> rag.v1.SearchResult
	0, // 5: rag.v1.RagService.Health:input_type -> rag.v1.HealthRequest
	2, // 6: rag.v1.RagService.ImportDocument:input_type -> rag.v1.ImportDocumentRequest
	4, // 7: rag.v1.RagService.Ask:input_type -> rag.v1.AskRequest
	1, // 8: rag.v1.RagService.Health:output_type -> rag.v1.HealthResponse
	3, // 9: rag.v1.RagService.ImportDocument:output_type -> rag.v1.ImportDocumentResponse
	5, // 10: rag.v1.RagService.Ask:output_type -> rag.v1.AskResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
