// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rag/v1/rag.proto

package ragv1

import (
	common "app/rag-api/api/rag/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *common.CommonResp     `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetResp() *common.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type ImportDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDocumentRequest) Reset() {
	*x = ImportDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDocumentRequest) ProtoMessage() {}

func (x *ImportDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDocumentRequest.ProtoReflect.Descriptor instead.
func (*ImportDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *ImportDocumentRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ImportDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *common.CommonResp     `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDocumentResponse) Reset() {
	*x = ImportDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDocumentResponse) ProtoMessage() {}

func (x *ImportDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDocumentResponse.ProtoReflect.Descriptor instead.
func (*ImportDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *ImportDocumentResponse) GetResp() *common.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *common.CommonResp     `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *AskResponse) GetResp() *common.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\"\x0f\n" +
	"\rHealthRequest\"8\n" +
	"\x0eHealthResponse\x12&\n" +
	"\x04resp\x18\x01 \x01(\v2\x12.common.CommonRespR\x04resp\"4\n" +
	"\x15ImportDocumentRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"@\n" +
	"\x16ImportDocumentResponse\x12&\n" +
	"\x04resp\x18\x01 \x01(\v2\x12.common.CommonRespR\x04resp\"=\n" +
	"\n" +
	"AskRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"M\n" +
	"\vAskResponse\x12&\n" +
	"\x04resp\x18\x01 \x01(\v2\x12.common.CommonRespR\x04resp\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer2\x95\x02\n" +
	"\n" +
	"RagService\x12O\n" +
	"\x06Health\x12\x15.rag.v1.HealthRequest\x1a\x16.rag.v1.HealthResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/health\x12q\n" +
	"\x0eImportDocument\x12\x1d.rag.v1.ImportDocumentRequest\x1a\x1e.rag.v1.ImportDocumentResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/documents/import\x12C\n" +
	"\x03Ask\x12\x12.rag.v1.AskRequest\x1a\x13.rag.v1.AskResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/v1/askB\x1eZ\x1capp/rag-api/api/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rag_v1_rag_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: rag.v1.HealthRequest
	(*HealthResponse)(nil),         // 1: rag.v1.HealthResponse
	(*ImportDocumentRequest)(nil),  // 2: rag.v1.ImportDocumentRequest
	(*ImportDocumentResponse)(nil), // 3: rag.v1.ImportDocumentResponse
	(*AskRequest)(nil),             // 4: rag.v1.AskRequest
	(*AskResponse)(nil),            // 5: rag.v1.AskResponse
	(*common.CommonResp)(nil),      // 6: common.CommonResp
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	6, // 0: rag.v1.HealthResponse.resp:type_name -> common.CommonResp
	6, // 1: rag.v1.ImportDocumentResponse.resp:type_name -> common.CommonResp
	6, // 2: rag.v1.AskResponse.resp:type_name -> common.CommonResp
	0, // 3: rag.v1.RagService.Health:input_type -> rag.v1.HealthRequest
	2, // 4: rag.v1.RagService.ImportDocument:input_type -> rag.v1.ImportDocumentRequest
	4, // 5: rag.v1.RagService.Ask:input_type -> rag.v1.AskRequest
	1, // 6: rag.v1.RagService.Health:output_type -> rag.v1.HealthResponse
	3, // 7: rag.v1.RagService.ImportDocument:output_type -> rag.v1.ImportDocumentResponse
	5, // 8: rag.v1.RagService.Ask:output_type -> rag.v1.AskResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
