// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: rag/v1/rag.proto

package ragv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationRagServiceAsk = "/rag.v1.RagService/Ask"
const OperationRagServiceHealth = "/rag.v1.RagService/Health"
const OperationRagServiceImportDocument = "/rag.v1.RagService/ImportDocument"

type RagServiceHTTPServer interface {
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ImportDocument(context.Context, *ImportDocumentRequest) (*ImportDocumentResponse, error)
}

func RegisterRagServiceHTTPServer(s *http.Server, srv RagServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/health", _RagService_Health0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/documents/import", _RagService_ImportDocument0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/ask", _RagService_Ask0_HTTP_Handler(srv))
}

func _RagService_Health0_HTTP_Handler(srv RagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRagServiceHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*HealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthResponse)
		return ctx.Result(200, reply)
	}
}

func _RagService_ImportDocument0_HTTP_Handler(srv RagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRagServiceImportDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportDocument(ctx, req.(*ImportDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportDocumentResponse)
		return ctx.Result(200, reply)
	}
}

func _RagService_Ask0_HTTP_Handler(srv RagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRagServiceAsk)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ask(ctx, req.(*AskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AskResponse)
		return ctx.Result(200, reply)
	}
}

type RagServiceHTTPClient interface {
	Ask(ctx context.Context, req *AskRequest, opts ...http.CallOption) (rsp *AskResponse, err error)
	Health(ctx context.Context, req *HealthRequest, opts ...http.CallOption) (rsp *HealthResponse, err error)
	ImportDocument(ctx context.Context, req *ImportDocumentRequest, opts ...http.CallOption) (rsp *ImportDocumentResponse, err error)
}

type RagServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRagServiceHTTPClient(client *http.Client) RagServiceHTTPClient {
	return &RagServiceHTTPClientImpl{client}
}

func (c *RagServiceHTTPClientImpl) Ask(ctx context.Context, in *AskRequest, opts ...http.CallOption) (*AskResponse, error) {
	var out AskResponse
	pattern := "/api/v1/ask"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRagServiceAsk),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RagServiceHTTPClientImpl) Health(ctx context.Context, in *HealthRequest, opts ...http.CallOption) (*HealthResponse, error) {
	var out HealthResponse
	pattern := "/api/v1/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRagServiceHealth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RagServiceHTTPClientImpl) ImportDocument(ctx context.Context, in *ImportDocumentRequest, opts ...http.CallOption) (*ImportDocumentResponse, error) {
	var out ImportDocumentResponse
	pattern := "/api/v1/documents/import"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRagServiceImportDocument),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
